name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Patch files with version
        run: |
          sed -i "s|/main/|/${GITHUB_REF_NAME}/|g" ytranslate.ipynb
          sed -i "s|readonly VERSION='.*'|readonly VERSION='${{ env.VERSION }}'|g" ytranslate.sh
      - name: Create Release Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: Release ${{ env.VERSION }}"
      - name: Update Tag
        run: |
          git tag -f ${{ github.ref_name }}
          git push origin ${{ github.ref_name }} -f
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.VERSION }}
          files: ytranslate.sh
          draft: false
          prerelease: false
